language: java
jdk:
  - oraclejdk8
script: 
- ./mvnw test -B
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
